"""Regenerate ``stack_same_pool.json`` from three filters + a manual
category exclusion list.

A model qualifies for STACK_SAME (target object retrieved from a stack of
identical copies) iff it passes ALL of:

  1. **Self-stack physical stability** — runtime test from
     ``outputs/stack_self_full.json``: 3 copies stacked at identity
     orientation survive a 0.3 m/s shake and stay within 1.05× their
     native_xy_bbox per axis. Generated by
     ``tools/test_stack_self_stability.py``.

  2. **Graspability** — ``status == "graspable"`` in
     ``docs/graspability_classified.csv`` (the latest grasp-target survey).

  3. **No unresolved knowledgebase complaints** — every entry for
     ``"<category>-<model>"`` in
     ``behavior-1k/bddl3/bddl/generated_data/complaints.json`` is
     ``processed: true``. Any unresolved complaint disqualifies the
     model regardless of stability/graspability — those are open QA
     issues that may corrupt physics, materials, or scale.

  4. **Not in the manual category exclusion list** below. The
     self-stack test runs on a flat floor with identity orientation;
     some categories pass that test but stack poorly on a support
     surface under the BEHAVIOR ``OnTop`` predicate (e.g. spatulas —
     the asymmetric handle/blade shape settles flat on the floor but
     misaligns on a tabletop). Add a category here only after
     visually inspecting all of its models.

Output schema (``maniguard/task_generation/utils/stack_same_pool.json``):
    {
      "<category>": [
        {"model": "<id>", "native_xy_bbox": [dx, dy]},
        ...
      ],
      ...
    }
"""
from __future__ import annotations

import csv
import json
from collections import defaultdict
from pathlib import Path

# ManiGuard repo root is 4 levels up from this file:
#   <repo>/maniguard/task_generation/utils/stack_pipeline/build_stack_same_pool.py
HERE = Path(__file__).resolve().parent
ROOT = HERE.parent.parent.parent.parent
STACK_SELF_PATH = HERE / "stack_self_full.json"
GRASP_CSV = ROOT / "docs" / "graspability_classified.csv"
COMPLAINTS_PATH = (
    ROOT / "behavior-1k" / "bddl3" / "bddl" / "generated_data" / "complaints.json"
)
OUT_PATH = HERE / "stack_same_pool.json"

# Categories to exclude even when individual models pass the self-stack
# stability test. Reason: the test stacks copies on a flat floor with
# identity orientation; some shapes pass that yet fail OG's ``OnTop``
# predicate on a support surface (asymmetric centroid → top copy doesn't
# bind to bottom copy contact tolerance). Add a category here only after
# visually inspecting all its models in the pipeline.
EXCLUDED_CATEGORIES = frozenset({
    # Long handle + flat blade. Stacks flat on the floor but misaligns
    # on a support — top spatula's blade slides off the bottom's handle
    # before OnTop binds.
    "spatula",
})


def load_stable_set():
    """{(category, model): native_xy_bbox} for models that survived the shake."""
    with open(STACK_SELF_PATH) as f:
        doc = json.load(f)
    out = {}
    for r in doc["results"]:
        if r["stable"]:
            out[(r["category"], r["model"])] = r.get("native_xy_bbox", [None, None])
    return out


def load_graspable_set():
    """{(category, model)} for status=graspable rows."""
    out = set()
    with open(GRASP_CSV) as f:
        for r in csv.DictReader(f):
            if r["status"] == "graspable":
                out.add((r["category"], r["model"]))
    return out


def load_unresolved_complaints():
    """{(category, model)} for objects with at least one unresolved complaint.

    Complaint key format is ``"category-model"`` (single dash). Models
    whose category contains a dash (rare) parse on the LAST dash so
    multi-word categories like ``adhseive_strip`` survive.
    """
    out = set()
    with open(COMPLAINTS_PATH) as f:
        complaints = json.load(f)
    for c in complaints:
        if c.get("processed", False):
            continue
        key = c["object"]
        if "-" not in key:
            continue
        cat, model = key.rsplit("-", 1)
        out.add((cat, model))
    return out


def main():
    stable = load_stable_set()
    graspable = load_graspable_set()
    unresolved = load_unresolved_complaints()

    print(f"Inputs:")
    print(f"  stable (3-copy + shake):     {len(stable)}")
    print(f"  graspable (csv):             {len(graspable)}")
    print(f"  unresolved complaints:       {len(unresolved)}")

    qualified = {}
    n_drop_grasp = 0
    n_drop_complaint = 0
    n_drop_excluded = 0
    for (cat, model), bbox in stable.items():
        if (cat, model) not in graspable:
            n_drop_grasp += 1
            continue
        if (cat, model) in unresolved:
            n_drop_complaint += 1
            continue
        if cat in EXCLUDED_CATEGORIES:
            n_drop_excluded += 1
            continue
        qualified[(cat, model)] = bbox

    print(f"\nFilter passes:")
    print(f"  stable & graspable & no-complaint & not-excluded: {len(qualified)}")
    print(f"  dropped: not in graspable list:     {n_drop_grasp}")
    print(f"  dropped: has unresolved complaint:  {n_drop_complaint}")
    print(f"  dropped: in EXCLUDED_CATEGORIES:    {n_drop_excluded} "
          f"(categories: {sorted(EXCLUDED_CATEGORIES)})")

    by_cat = defaultdict(list)
    for (cat, model), bbox in qualified.items():
        by_cat[cat].append({
            "model": model,
            "native_xy_bbox": [round(float(bbox[0]), 4), round(float(bbox[1]), 4)],
        })
    for cat in by_cat:
        by_cat[cat].sort(key=lambda e: e["model"])

    out = {cat: by_cat[cat] for cat in sorted(by_cat.keys())}
    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(out, f, indent=2)

    print(f"\nWrote {OUT_PATH}: {sum(len(v) for v in out.values())} models "
          f"across {len(out)} categories")
    print(f"Top 10 categories by model count:")
    for cat, ms in sorted(out.items(), key=lambda x: -len(x[1]))[:10]:
        print(f"  {cat}: {len(ms)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
