name: mug_into_bowl_sim2real

benchmark_root: outputs/eval_benchmarks/mug_into_bowl_jixin
scene_filter: ""

host: 127.0.0.1
port: 8000
use_openpi_client: true

state_mode: eef_8d_axisangle
policy_cameras: [cam_opposite]
action_dim: 7
execute_horizon: 5
gripper_binarize: true

max_steps: 1000
camera_resolution: 256
save_video: true
longfinger: false

output_dir: outputs/eval_mug_bowl

checkpoint: vla_models/sim2real_mug_pi05/checkpoints/pi05_clutter_libero_lora/sim2real_mug_from_sim_table_25000_30k/30000
serve_config_name: pi05_clutter_libero_lora
