"""Build lid_transport_food_compat.json — kept (lid|cap, container) pairs
joined with the foods that fit inside each container.

Inputs:
  * ``lid_cap_container_pairs.json`` (this folder) — auto-derived inventory
    with per-pair status + verdict. Generated by
    ``build_lid_cap_container_pairs.py``.
  * ``utils/transfer_compatibility.json`` — built by
    ``tools/build_transfer_compatibility.py``. Per container, lists food
    models that satisfy ``max(food.bbox_dims) <= container.opening_minor``,
    pre-filtered to graspable foods with ``food_transfer_target`` set.

Filter: pairs are admitted iff ``verdict ∈ {kept, kept_via_relax}`` OR
either side has ``status == "manually_added"`` (escape hatch for
hand-added rows). Containers not in ``transfer_compatibility.json`` (e.g.
narrow-mouth bottles caps screw onto) are dropped here — no food data to
join.

Schema: category-first → model-keyed → containers list, with foods
restructured ``{food_cat: [model, ...]}`` so a runtime sampler can do
uniform-random-cat then uniform-random-model and avoid the ``hardback
has 245 entries`` bias.

  {
    "metadata": {... source paths, counts ...},
    "lid": {
      "<lid_model>": [
        {
          "container_category": "...",
          "container_model": "...",
          "opening_square_side_m": 0.123,
          "opening_centroid_xy_relative_to_aabb_center_m": [dx, dy],
          "opening_floor_z_above_aabb_min_m": 0.0,
          "opening_floor_depth_below_aabb_top_m": 0.0,
          "n_food_categories": int,
          "n_food_models": int,
          "foods": {"<food_cat>": ["<food_model>", ...], ...}
        },
        ...
      ],
      ...
    },
    "cap": { ... }
  }
"""
from __future__ import annotations

import json
from collections import defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
PAIRS_PATH = HERE / "lid_cap_container_pairs.json"
TRANSFER_COMPAT_PATH = HERE.parent / "food_transfer_pipeline" / "transfer_compatibility.json"
OUT_PATH = HERE / "lid_transport_food_compat.json"

ITEM_CATEGORIES = ("lid", "cap")
KEEP_VERDICTS = frozenset({"kept", "kept_via_relax"})
MANUAL_STATUS = "manually_added"


def is_admitted(item_status, container_entry):
    """A pair is admitted if its verdict is kept/kept_via_relax, OR either
    side carries the manually_added marker (so hand-edits override the
    derived verdict)."""
    if item_status == MANUAL_STATUS:
        return True
    if container_entry.get("status") == MANUAL_STATUS:
        return True
    return container_entry.get("verdict") in KEEP_VERDICTS


def load_pairs():
    return json.load(open(PAIRS_PATH))


def load_transfer_compat():
    """Return {(cat, model) -> compat_entry} for fast lookup."""
    raw = json.load(open(TRANSFER_COMPAT_PATH))
    return {(v["category"], v["model"]): v for v in raw.values()}


def restructure_foods(food_models):
    """Turn the flat list ``[{category, model}, ...]`` into ``{cat: [models]}``."""
    out = defaultdict(list)
    for f in food_models:
        out[f["category"]].append(f["model"])
    for cat in out:
        out[cat].sort()
    return {cat: out[cat] for cat in sorted(out.keys())}


def main():
    pairs = load_pairs()
    tc = load_transfer_compat()

    out_doc = {"metadata": {
        "source_pairs": str(PAIRS_PATH.relative_to(HERE.parent.parent.parent)),
        "source_transfer_compat":
            str(TRANSFER_COMPAT_PATH.relative_to(HERE.parent.parent.parent)),
        "keep_verdicts": sorted(KEEP_VERDICTS),
        "manual_status_marker": MANUAL_STATUS,
    }}

    counts = defaultdict(lambda: defaultdict(int))
    for item_cat in ITEM_CATEGORIES:
        per_model = {}
        for item_model, info in pairs[item_cat].items():
            item_status = info["item_status"]
            kept = []
            for c in info["containers"]:
                if not is_admitted(item_status, c):
                    counts[item_cat]["pair_dropped_verdict"] += 1
                    continue
                cc, cm = c["category"], c["model"]
                tc_entry = tc.get((cc, cm))
                if tc_entry is None:
                    counts[item_cat]["pair_dropped_no_transfer_data"] += 1
                    continue
                foods = tc_entry.get("food_models") or []
                if not foods:
                    counts[item_cat]["pair_dropped_no_food"] += 1
                    continue
                foods_by_cat = restructure_foods(foods)
                kept.append({
                    "container_category": cc,
                    "container_model": cm,
                    "opening_square_side_m": float(tc_entry.get("opening_square_side_m", 0.0)),
                    "opening_centroid_xy_relative_to_aabb_center_m":
                        list(tc_entry.get(
                            "opening_centroid_xy_relative_to_aabb_center_m", [0.0, 0.0])),
                    "opening_floor_z_above_aabb_min_m":
                        float(tc_entry.get("opening_floor_z_above_aabb_min_m", 0.0)),
                    "opening_floor_depth_below_aabb_top_m":
                        float(tc_entry.get("opening_floor_depth_below_aabb_top_m", 0.0)),
                    "n_food_categories": len(foods_by_cat),
                    "n_food_models": sum(len(v) for v in foods_by_cat.values()),
                    "foods": foods_by_cat,
                })
                counts[item_cat]["pair_kept"] += 1
            if kept:
                # Sort containers by model for diff-friendly output.
                kept.sort(key=lambda e: (e["container_category"], e["container_model"]))
                per_model[item_model] = kept
        out_doc[item_cat] = {k: per_model[k] for k in sorted(per_model)}

    out_doc["metadata"]["counts"] = {k: dict(v) for k, v in counts.items()}
    out_doc["metadata"]["totals"] = {
        item_cat: {
            "item_models": len(out_doc[item_cat]),
            "container_pairs": sum(len(v) for v in out_doc[item_cat].values()),
            "food_pair_count": sum(
                e["n_food_models"]
                for v in out_doc[item_cat].values()
                for e in v
            ),
        }
        for item_cat in ITEM_CATEGORIES
    }

    with open(OUT_PATH, "w") as f:
        json.dump(out_doc, f, indent=2)

    print(f"Wrote {OUT_PATH}")
    for item_cat in ITEM_CATEGORIES:
        t = out_doc["metadata"]["totals"][item_cat]
        c = counts[item_cat]
        print(f"\n{item_cat}: {t['item_models']} item models, "
              f"{t['container_pairs']} (item, container) pairs, "
              f"{t['food_pair_count']} (item, container, food_model) triples")
        for k, n in sorted(c.items()):
            print(f"  {k:38s} {n}")


if __name__ == "__main__":
    main()
